services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/local/docker/data/nginx/build:/home
      - /usr/local/docker/data/nginx/logs:/logs
      - /usr/local/docker/data/nginx/conf:/etc/nginx/conf.d
      - /usr/local/docker/data/certbot/conf:/etc/letsencrypt
      - /usr/local/docker/data/certbot/www:/var/www/certbot
    depends_on:
      - moa-dev
      - db

  certbot:
    container_name: certbot
    image: "certbot/certbot"
    volumes:
      - /usr/local/docker/data/certbot/conf:/etc/letsencrypt
      - /usr/local/docker/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  moa-dev:
    container_name: moa-dev
#    image: moa-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /usr/local/docker/data/app/logs:/home/spring/logs
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data:
