spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/server2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ON_SECRET
    password: ON_SECRET
    hikari:
      connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect