spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://3.35.1.56:3306/server2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL8Dialect
