name: cd

on:
  pull_request:
    branches:
      - dev2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

      - name: create application.yml
        run: |
          echo '${{ secrets.DEV_APPLICATION_YML }}' > src/main/resources/application.yml

      - name: create application-secret.yml
        run: |
          touch src/main/resources/application-secret.yml
          echo '${{ secrets.DEV_APPLICATION_SECRET_YML }}' >> src/main/resources/application-secret.yml

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.AWS_ECR_REGISTRY }}
          region: ap-northeast-2
          mask-password: true

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:${{ github.sha }} .
          docker tag ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:${{ github.sha }} ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:${{ github.sha }}
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: SSH Commands to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: ${{ secrets.LIGHTSAIL_PORT }}
          script: |
            docker pull ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:latest
            docker stop moa-be || true
            docker rm moa-be || true
            docker run -d --name moa-be -p 80:80 ${{ secrets.AWS_ECR_REGISTRY }}/moa-be:latest
